name: Docker Prod Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile.prod --tag varungujarathi9/video-party-server:latest
      - name: Login to docker
        run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push varungujarathi9/video-party-server:latest
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: custom
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #     custom_payload: |
      #       {
      #         username: 'action-slack',
      #         icon_emoji: ':octocat:',
      #         attachments: [{
      #           color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
      #           text: `${{github.repository}}\n${process.env.AS_WORKFLOW}\nJob status : ${{ job.status }}`,
      #         }]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      #   if: always() # Pick up events even if the job fails or is canceled.

