FROM python:3.6-slim
COPY . /server
WORKDIR /server
RUN cp configs.uat.json configs.json
RUN pip install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["gunicorn", "--config", "gunicorn_config.py", "server_prod:app"]