# pull official base image
FROM python:3.6-slim

# set working directory
WORKDIR /server
RUN apt-get update
RUN apt-get install gcc python3-dev
# install app dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

# add app
COPY . ./

# replace config file
RUN cp configs.sit.json configs.json

EXPOSE 5000
# start app
CMD ["python3", "server_rest.py"]

