version: '3.7'

services:

  watchtower:
    container_name: watchtower
    image: index.docker.io/containrrr/watchtower:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.docker/config.json:/config.json'
    restart: unless-stopped
    environment: 
      - WATCHTOWER_NOTIFICATIONS=slack
      - 'WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/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'
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Docker_Watchtower
      - 'WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#updates'
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=60

  coturn_server:
    image: instrumentisto/coturn:4.5.1
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/turnserver.conf:/etc/coturn/turnserver.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #
  #   depends_on:
  #     - clientprod
  #   command: certonly --webroot --webroot-path=/var/www/html --email v.gujarathi777@gmail.com --agree-tos --no-eff-email --force-renewal -d videoparty.tk  -d www.videoparty.tk

  clientsit:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientsit
    image: index.docker.io/varungujarathi9/video-party-client:sit
    restart: unless-stopped
    ports:
      - 3001:3000
    
  clientuat:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientuat
    image: index.docker.io/varungujarathi9/video-party-client:uat
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    restart: unless-stopped
    ports:
      - 3002:443

  clientprod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: clientprod
    image: index.docker.io/varungujarathi9/video-party-client:latest
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 443:443 

  serversit:
    # container_name: video-party-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serversit
    image: index.docker.io/varungujarathi9/video-party-server:sit
    restart: unless-stopped
    ports:
      - 5001:5000

  serveruat:
    # container_name: video-party-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serveruat
    image: index.docker.io/varungujarathi9/video-party-server:uat
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    restart: unless-stopped
    ports:
      - 5002:443

  serverprod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: serverprod
    image: index.docker.io/varungujarathi9/video-party-server:latest
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 1793:443

volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
  certbot-var:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/letsencrypt
      o: bind

